### ISSUE TITLE
groupBy query on Android 7.* gives `CouchbaseLiteException{CouchbaseLite,12,'disk I/O error'}`

### ISSUE THREAD

**Issue by dtchepak** [couchbase/couchbase-lite-java-ce-root#4]
On a Nexus 5X running Android 7.1.2 *, I've found using `groupBy` reliably fails with a `CouchbaseLiteException{CouchbaseLite,12,'disk I/O error'}` exception once a certain data size is reached. This is running CBL 2.7.0; the same query worked without error on CBL 2.6.2.

I've created a [sample app to reproduce this](https://github.com/dtchepak/android-workshop/tree/cbl-groupby-ioexception) (`cbl-groupby-ioexception` branch).

\* EDIT: Further testing seems to show Android 7.* devices are affected. Was also able to reproduce on emulated devices running Android 7.1.1 and 7.0, but not on devices running Android 8 or 10.

## Steps

* Build and run app on a real or emulated device running Android 7.x (tests on other devices/Android versions pending, see "Repro notes" below)
* Click "CBL Example" button
* Click "Insert" and wait until it completes ("Status" text will update).
* Click "Query" and wait until it completes. Status will update to show the result of a (silly) groupBy query.
* Click "Insert" and wait until it completes, then do so one more time. This will mean there are 3000 records in the database.
* Click "Query" and wait until it completes. This should result in a `CouchbaseLiteException{CouchbaseLite,12,'disk I/O error'}` exception. Attached debugger shows the following:

```
2020-02-04 18:15:44.900 21756-21756/net.davesquared.androidworkshop E/CblActivity: Query failed
    CouchbaseLiteException{CouchbaseLite,12,'disk I/O error'}
        at com.couchbase.lite.internal.CBLStatus.convertException(CBLStatus.java:92)
        at com.couchbase.lite.internal.CBLStatus.convertException(CBLStatus.java:46)
        at com.couchbase.lite.AbstractQuery.execute(AbstractQuery.java:139)
        at com.couchbase.lite.GroupBy.execute(GroupBy.java:32)
        at net.davesquared.androidworkshop.CblActivity$runQuery$1.call(CblActivity.kt:134)
...
     Caused by: LiteCoreException{domain=1, code=12, msg=disk I/O error}
        at com.couchbase.lite.internal.core.C4Query.run(Native Method)
        at com.couchbase.lite.internal.core.C4Query.run(C4Query.java:140)
        at com.couchbase.lite.AbstractQuery.execute(AbstractQuery.java:134)
        at com.couchbase.lite.GroupBy.execute(GroupBy.java:32) 
        at net.davesquared.androidworkshop.CblActivity$runQuery$1.call(CblActivity.kt:134) 
...
```

## Record insertion code

https://github.com/dtchepak/android-workshop/blob/496c02f02110a91c15f94677b2d5815aa67d6a8b/app/src/main/java/net/davesquared/androidworkshop/CblActivity.kt#L106-L121

```
    private fun runInsert() = Single.fromCallable {
        val data = (0..1000).joinToString(",")
        repeat(1) { // <- Change to vary how many batches of 1000 records are inserted. On Nexus 5X, 3000 records are enough to trigger i/o exception for query
            database.inBatch {
                repeat(1000) {
                    val p = randomPokemon()
                    val doc = MutableDocument()
                    // When `data` field is removed, more records are required to trigger i/o exception for query.
                    doc.setString("data", data)
                    doc.setString("type", p)
                    database.save(doc)
                }
            }
        }
        database.count
    }
```

Some notes (see code comments):
* 3000 records are enough to break the groupBy queries on the 5X
* The inserted documents are of the form `{ "data": "0,1,2,...", "type": "randomSelectionFromList" }`.
* Removing the `data` field means more records need to be added before `groupBy` queries start breaking. It seems the size of the document is relevant to the issue occurring. Note the `data` field is not used at all in the query (see below).

## Query code

https://github.com/dtchepak/android-workshop/blob/496c02f02110a91c15f94677b2d5815aa67d6a8b/app/src/main/java/net/davesquared/androidworkshop/CblActivity.kt#L123-L141

```
    private fun runQuery() = Single.fromCallable {
        val result = QueryBuilder
            .select(
                SelectResult.property("type"),
                SelectResult.expression(Function.count(Expression.string("*")))
            )
            .from(
                DataSource.database(database)
            )
            // Removing .groupBy causes query to work without i/o exception
            .groupBy(Expression.property("type"))
            .execute()


        result.allResults()
            .sortedBy { it.getInt(1) }
            .joinToString("\n") { r ->
                "${r.getString("type")} ${r.getInt(1)}"
            }
    }
```

As commented, removing the `groupBy` causes the query to start working again (although the result just includes a count with a single record as the grouping no longer occurs).

## Repro notes

So far I have only been able to reproduce this on:

* Nexus 5X running Android 7.1.2 (2GB RAM)
* Emulated devices running Android 7.1.1 API 25 Play Store AVD image. (Nexus 5X, Pixel 3a, and Pixel)
* Emulated devices running Android 7.0 API 24 Play Store AVD image.

I have not been able to reproduce it on:

* Emulated devices running Android 8 (Play Store AVD image)
* Pixel 2XL running Android 10 (even with hundreds of thousands of records)
* Using CBL 2.6.2.

Although I could not reproduce this on Android 10, I did find the following exception sometimes when running the query over very large data sets:

```
2020-02-04 14:46:31.263 16324-16340/net.davesquared.androidworkshop E/AndroidRuntime: FATAL EXCEPTION: FinalizerWatchdogDaemon
    Process: net.davesquared.androidworkshop, PID: 16324
    java.util.concurrent.TimeoutException: com.couchbase.lite.ResultSet.finalize() timed out after 10 seconds
        at com.couchbase.lite.ResultSet.free(ResultSet.java:190)
        at com.couchbase.lite.ResultSet.finalize(ResultSet.java:146)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
        at java.lang.Daemons$Daemon.run(Daemons.java:137)
        at java.lang.Thread.run(Thread.java:919
```

On the Nexus 5X I would occasionally observe the following exception:

```
2020-02-04 16:59:49.660 12252-12263/net.davesquared.androidworkshop E/AndroidRuntime: FATAL EXCEPTION: FinalizerWatchdogDaemon
    Process: net.davesquared.androidworkshop, PID: 12252
    java.util.concurrent.TimeoutException: com.couchbase.lite.GroupBy.finalize() timed out after 10 seconds
        at com.couchbase.lite.AbstractQuery.free(AbstractQuery.java:383)
        at com.couchbase.lite.AbstractQuery.finalize(AbstractQuery.java:222)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
        at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
        at java.lang.Thread.run(Thread.java:761
```

## Possibly related

* https://forums.couchbase.com/t/disk-i-o-error-while-executing-query/20864: same exception on pre-CBL 2.5.0 from April 2019 that also involved a `groupBy` query on Android. Possibly a regression in 2.7.0?

**Comment by bmeike** [comment]
Sorry this took so long.  It has been fixed in >= 2.7.1
